/home/runhua/xen-4.11-experiment/xen/.xen-syms.0.o: \
 .xen-syms.0.S \
 include/xen/config.h \
 include/xen/kconfig.h \
 include/generated/autoconf.h \
 include/asm/config.h \
 include/xen/const.h \
 include/xen/config.h \
 include/asm/types.h
