/home/runhua/xen-4.11-experiment/xen/.xen.efi.0s.o: \
 .xen.efi.0s.S \
 include/xen/config.h \
 include/xen/kconfig.h \
 include/generated/autoconf.h \
 include/asm/config.h \
 include/xen/const.h \
 include/xen/config.h \
 include/asm/types.h
