boot.o: boot.c /home/runhua/xen-4.11-experiment/xen/include/xen/config.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/kconfig.h \
 /home/runhua/xen-4.11-experiment/xen/include/generated/autoconf.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/compiler.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/init.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/init.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/config.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/const.h efi.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/efibind.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/types.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/stdbool.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/types.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/x86_64/efibind.h \
 /home/runhua/xen-4.11-experiment/xen/include/efi/efidef.h \
 /home/runhua/xen-4.11-experiment/xen/include/efi/efierr.h \
 /home/runhua/xen-4.11-experiment/xen/include/efi/eficon.h \
 /home/runhua/xen-4.11-experiment/xen/include/efi/efidevp.h \
 /home/runhua/xen-4.11-experiment/xen/include/efi/eficapsule.h \
 /home/runhua/xen-4.11-experiment/xen/include/efi/efiapi.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/efi.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/spinlock.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/system.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/lib.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/inttypes.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/stdarg.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/xmalloc.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/cache.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/cache.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/string.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/string.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/bug.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/bitops.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/bitops.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/alternative.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/alternative-asm.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/nops.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/stringify.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/cpufeatureset.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/arch-x86/cpufeatureset.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/cpufeatures.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/cpuid-autogen.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/processor.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/smp.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/smp.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/kernel.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/cpumask.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/bitmap.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/random.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/current.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/percpu.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/percpu.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/xen.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/xen-compat.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/arch-x86/xen.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/arch-x86/../xen.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/arch-x86/xen-x86_64.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/page.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/x86_64/page.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/pdx.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/mpspec.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/mpspec_def.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm-x86/mach-default/mach_mpspec.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/cpufeature.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/cpuid.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/x86_emulate.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/regs.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/x86_64/regs.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/../../arch/x86/x86_emulate/x86_emulate.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/sysctl.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/xen.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/domctl.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/event_channel.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/grant_table.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/hvm/save.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/hvm/../arch-x86/hvm/save.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/memory.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/physdev.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/tmem.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/desc.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/x86-defns.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/x86-vendors.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/x86_64/system.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/spinlock.h \
 /home/runhua/xen-4.11-experiment/xen/include/efi/efiprot.h \
 /home/runhua/xen-4.11-experiment/xen/include/efi/efipciio.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/compile.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/ctype.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/dmi.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/keyhandler.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/mm.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/list.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/prefetch.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/typesafe.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/perfc.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/memory.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/mm.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/rwlock.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/atomic.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/atomic.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/io.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/vmap.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/uaccess.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/errno.h \
 /home/runhua/xen-4.11-experiment/xen/include/public/errno.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/asm_defns.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/asm-offsets.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/spec_ctrl_asm.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/x86_64/uaccess.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/flushtlb.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/multiboot.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/const.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/pci_regs.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/pfn.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/fixmap.h efi-boot.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/vga.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/video.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/e820.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/edd.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/msr.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/msr-index.h
