efi/relocs-dummy.o: efi/relocs-dummy.S \
 /home/runhua/xen-4.11-experiment/xen/include/xen/config.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/kconfig.h \
 /home/runhua/xen-4.11-experiment/xen/include/generated/autoconf.h \
 /home/runhua/xen-4.11-experiment/xen/include/asm/config.h \
 /home/runhua/xen-4.11-experiment/xen/include/xen/const.h
