# Automatically generated by configure - do not modify
SRC_PATH=/home/runhua/xen-4.11-experiment/tools/qemu-xen/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
